# Generated by Django 2.2.2 on 2019-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microBlogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
