# Generated by Django 2.2.2 on 2019-06-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microBlogger', '0003_auto_20190629_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='description',
            new_name='content',
        ),
    ]
