# Generated by Django 2.2.2 on 2019-07-01 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('microBlogger', '0005_blogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
