# Generated by Django 2.2.2 on 2019-07-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microBlogger', '0006_auto_20190701_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
